### ISSUE TITLE
apps not working since updated on play store

### ISSUE THREAD

**Issue by 19rocl86** [nextux/iview-android-tv#10]
Videos are showing up on both apps, however ever since the iView & SBS were updated on the play store in late April no video loads when selected and it gets an error message.

**Comment by nextux** [comment]
I don't have these released on the Google Play Store and have no intention of doing so. Right now, both ABC and SBS have turned a blind eye to these projects. I'm sure they are aware of their existence.  However I'm curious as to what you have mentioned as of these apps are being distributed on the Play Store, because if they are, I'd like to see who and what modifications have been made. The only download I make of these apps is via GitHub and sideloadtag.

Being said, should either ABC or SBS release an official Android TV app or interface within their current app, these projects would be discontinued upon their release.
